language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - master

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
  - cd cmd/cortexbot
  - CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH" -a -installsuffix cgo
