language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - master

script:
  - cd cmd/cortexbot
  - CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH" -a -installsuffix cgo
